import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  addcontainer: {
    height: "100%",
    width: "100%",
    display: "flex",
  },
  closeicon: {
    width: 40,
    height: 40,
    padding: 10,
    alignItems: "center",
    borderRadius: 20,
    alignSelf: "flex-end",
    marginRight: 20,
    borderWidth: 1,
    borderColor: "grey",
    marginTop: 70,
  },
  input: {
    //borderColor:'none',
    width: "80%",
    alignSelf: "center",
    position: "absolute",
    top: "40%",
    padding: 20,
  },
  firsticons: {
    flexDirection: "row",
    position: "absolute",
    top: "48%",
  },
  calender: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "grey",
    padding: 10,
    width: 120,
    alignItems: "center",
    justifyContent: "space-evenly",
    borderRadius: 35,
    marginLeft: 50,
  },
  calendertxt: {
    color: "grey",
    fontSize: 17,
  },
  circle: {
    borderColor: "grey",
    borderWidth: 1,
    //padding:5,
    marginLeft: 20,
    width: 40,
    height: 40,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 3,
  },
  circle2: {
    borderColor: "blue",
    borderWidth: 2,
    borderRadius: 13,
    width: 25,
    height: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  circle3: {
    backgroundColor: "deeppink",
    borderRadius: 10,
    height: 15,
    width: 15,
  },
  icons: {
    flexDirection: "row",
    position: "absolute",
    bottom: "28%",
    width: "40%",
    justifyContent: "space-between",
    alignItems: "center",
    marginLeft: 120,
  },
  newtask: {
    flexDirection: "row",
    position: "absolute",
    bottom: "8%",
    backgroundColor: "blue",
    width: "40%",
    justifyContent: "center",
    height: 50,
    alignItems: "center",
    borderRadius: 240,
    alignSelf: "flex-end",
    right: 15,
    shadowColor: "blue",
    shadowOpacity: 0.3,
    shadowRadius: 8,
    shadowOffset: {
      height: 2,
      width: 0,
    },
    elevation: 1,
  },
  newtasktxt: {
    color: "#fff",
    fontSize: 16,
  },
});

export default styles;
